spring:
  application:
    name: wechat-service
  profiles:
    active: dev

server:
  port: 81
  servlet:
    context-path: /wechat


mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml

logging:
  config: classpath:log2j.xml

service:
  num: 1
  code: wechat-service
  name: 微信服务


